name       : haskell-system-fileio
version    : 0.3.16.3
release    : 1
source     :
    - http://hackage.haskell.org/package/system-fileio-0.3.16.3/system-fileio-0.3.16.3.tar.gz : 3175707cb322c65760fa2eb2ab17327f251c8294ad688efc6258e82328830491
license    : MIT
component  : programming.haskell
summary    : This is a small wrapper around the directory, unix, and Win32 packages, for use with system-filepath.
description: |
    This is a small wrapper around the directory, unix, and Win32 packages, for use with system-filepath.
builddeps  :
    - haskell-cabal-install
    - haskell-system-filepath
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
