name       : haskell-system-fileio
version    : 0.3.16.4
release    : 4
source     :
    - https://hackage.haskell.org/package/system-fileio-0.3.16.4/system-fileio-0.3.16.4.tar.gz : 34e58b88a19a69ff1a559e211af6edb596e33ee1b1d5f44490febf325c78c6c7
license    : MIT
component  : programming.haskell
summary    : This is a small wrapper around the directory, unix, and Win32 packages, for use with system-filepath.
description: |
    This is a small wrapper around the directory, unix, and Win32 packages, for use with system-filepath.
builddeps  :
    - haskell-cabal-install
    - haskell-system-filepath-devel
rundeps    :
    - devel:
        - haskell-system-filepath-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
